#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import yaml


def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding='utf-8')) or {}


def render(data: dict) -> str:
    cuow = data.get('canonical_unit_of_work', {})
    lines = ['# Cost of Running', '', '## Canonical unit of work', '']
    lines.append(f"- Name: **{cuow.get('name', 'unknown')}**")
    if cuow.get('description'):
        lines.append(f"- Description: {cuow.get('description')}")
    lines.append('')
    lines.append('Generated by the NextEco skill helper.')
    return '
'.join(lines) + '
'


def main() -> int:
    parser = argparse.ArgumentParser(description='Render Markdown from a NextEco YAML model')
    parser.add_argument('input', nargs='?', default='cost_of_running.yaml')
    parser.add_argument('--output', default='cost_of_running.md')
    args = parser.parse_args()
    content = render(load_yaml(Path(args.input)))
    Path(args.output).write_text(content, encoding='utf-8')
    print(f'Rendered {args.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
